### ISSUE TITLE
Request: Document

### ISSUE THREAD

**Issue by semsphy** [bavix/laravel-xhprof#8]
Would you please update the document?

**Comment by rez1dent3** [comment]
Hi, Can I have more details?

**Comment by semsphy** [comment]
Hi @rez1dent3 ,

I installed the package, but I can't get it works.

**Comment by rez1dent3** [comment]
You need to install xhprof, and then configure it to your needs.
https://github.com/bavix/laravel-xhprof/blob/a4144494a5da731dbff4d003e2e31ea1c68a670d/config/config.php#L4-L11

**Comment by semsphy** [comment]
`'path' => '/opt/xhprof', ` the lib of xhprof was not included in this package. where can I get it?

I debugged  https://github.com/bavix/laravel-xhprof/blob/a4144494a5da731dbff4d003e2e31ea1c68a670d/src/Services/XHProfService.php#L34  and it is never true.

**Comment by rez1dent3** [comment]
> `'path' => '/opt/xhprof', ` the lib of xhprof was not included in this package. where can I get it?

Xhprof source path

> and it is never true.

You are not right

**Comment by semsphy** [comment]
Ok, I will try again. How  can I  show the result of profiling?

**Comment by semsphy** [comment]
I want to confirm one more thing, If I use the `tideway`, the lib from xhprof still works?

**Comment by rez1dent3** [comment]
> Ok, I will try again. How can I show the result of profiling?

expand and configure
https://github.com/longxinH/xhprof/tree/master/xhprof_html

**Comment by semsphy** [comment]
> > `'path' => '/opt/xhprof', ` the lib of xhprof was not included in this package. where can I get it?
> 
> Xhprof source path
> 
> > and it is never true.
> 
> You are not right

```bash
>>> config('xhprof.freq', 0.01);
=> 0.001
>>> mt_rand() / mt_getrandmax()
=> 0.75573935301776
```

I followed the default configuration, you see the `0.001 >= 0.7555` ,  I tested many time it is never true. How can I tweak to make it works in term of best practice?

**Comment by rez1dent3** [comment]
> I followed the default configuration, you see the 0.001 >= 0.7555 , I tested many time it is never true. How can I tweak to make it works in term of best practice?

![Screenshot from 2020-07-07 12-36-33](https://user-images.githubusercontent.com/5111255/86761275-833cbf80-c04e-11ea-8f72-2bd6b7bce465.png)

I log not all requests, but only one thousandth. 

![Screenshot from 2020-07-07 12-37-40](https://user-images.githubusercontent.com/5111255/86761486-ab2c2300-c04e-11ea-9c79-34616d8bb90a.png)
And here is how it works on production.

**Comment by semsphy** [comment]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/423396/86763770-c2c8d300-c071-11ea-9222-384f13df76f9.png">

From cli it works. What is the purpose of `freq`?

**Comment by semsphy** [comment]
If I changed the `freq` => `1` in `xhprof.php` I can produce the output, any idea?

<img width="693" alt="image" src="https://user-images.githubusercontent.com/423396/86764856-9bbed100-c072-11ea-8662-2bbf46a8cb7a.png">

**Comment by rez1dent3** [comment]
> What is the purpose of freq?

xhprof can be used in production. To reduce the load, I log part of the requests. That there was no overhead

**Comment by semsphy** [comment]
> > What is the purpose of freq?
> 
> xhprof can be used in production. To reduce the load, I log part of the requests. That there was no overhead

I changed my freq to 1 to make it works, it is not a good idea?

**Comment by rez1dent3** [comment]
> I changed my freq to 1 to make it works, it is not a good idea?

Depends on your load. I would advise no more than 1% of requests

**Comment by semsphy** [comment]
> > I changed my freq to 1 to make it works, it is not a good idea?
> 
> Depends on your load. I would advise no more than 1% of requests

A million thanks @rez1dent3 for guiding me to get it works. I will try to adjust the `freq` accordingly.
